[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_manager = "4jne4voX6MxJHP4Q2eUBHZ6uNc8WjzynnuhFXrREBEGd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/derlys/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
